
#pragma once


#include <glesbinding/nogles.h>

#include <glesbinding/gles/bitfield.h>


namespace gles31ext
{


// import bitfields to namespace
using gles::GL_ALL_SHADER_BITS_EXT;
using gles::GL_BOLD_BIT_NV;
using gles::GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT_EXT;
using gles::GL_CLIENT_STORAGE_BIT_EXT;
using gles::GL_CONTEXT_FLAG_DEBUG_BIT;
using gles::GL_CONTEXT_FLAG_DEBUG_BIT_KHR;
using gles::GL_CONTEXT_FLAG_NO_ERROR_BIT_KHR;
using gles::GL_CONTEXT_FLAG_PROTECTED_CONTENT_BIT_EXT;
using gles::GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT;
using gles::GL_COVERAGE_BUFFER_BIT_NV;
using gles::GL_DYNAMIC_STORAGE_BIT_EXT;
using gles::GL_FONT_ASCENDER_BIT_NV;
using gles::GL_FONT_DESCENDER_BIT_NV;
using gles::GL_FONT_HAS_KERNING_BIT_NV;
using gles::GL_FONT_HEIGHT_BIT_NV;
using gles::GL_FONT_MAX_ADVANCE_HEIGHT_BIT_NV;
using gles::GL_FONT_MAX_ADVANCE_WIDTH_BIT_NV;
using gles::GL_FONT_NUM_GLYPH_INDICES_BIT_NV;
using gles::GL_FONT_UNDERLINE_POSITION_BIT_NV;
using gles::GL_FONT_UNDERLINE_THICKNESS_BIT_NV;
using gles::GL_FONT_UNITS_PER_EM_BIT_NV;
using gles::GL_FONT_X_MAX_BOUNDS_BIT_NV;
using gles::GL_FONT_X_MIN_BOUNDS_BIT_NV;
using gles::GL_FONT_Y_MAX_BOUNDS_BIT_NV;
using gles::GL_FONT_Y_MIN_BOUNDS_BIT_NV;
using gles::GL_FRAGMENT_SHADER_BIT_EXT;
using gles::GL_GEOMETRY_SHADER_BIT;
using gles::GL_GEOMETRY_SHADER_BIT_EXT;
using gles::GL_GEOMETRY_SHADER_BIT_OES;
using gles::GL_GLYPH_HAS_KERNING_BIT_NV;
using gles::GL_GLYPH_HEIGHT_BIT_NV;
using gles::GL_GLYPH_HORIZONTAL_BEARING_ADVANCE_BIT_NV;
using gles::GL_GLYPH_HORIZONTAL_BEARING_X_BIT_NV;
using gles::GL_GLYPH_HORIZONTAL_BEARING_Y_BIT_NV;
using gles::GL_GLYPH_VERTICAL_BEARING_ADVANCE_BIT_NV;
using gles::GL_GLYPH_VERTICAL_BEARING_X_BIT_NV;
using gles::GL_GLYPH_VERTICAL_BEARING_Y_BIT_NV;
using gles::GL_GLYPH_WIDTH_BIT_NV;
using gles::GL_ITALIC_BIT_NV;
using gles::GL_MAP_COHERENT_BIT_EXT;
using gles::GL_MAP_FLUSH_EXPLICIT_BIT_EXT;
using gles::GL_MAP_INVALIDATE_BUFFER_BIT_EXT;
using gles::GL_MAP_INVALIDATE_RANGE_BIT_EXT;
using gles::GL_MAP_PERSISTENT_BIT_EXT;
using gles::GL_MAP_READ_BIT_EXT;
using gles::GL_MAP_UNSYNCHRONIZED_BIT_EXT;
using gles::GL_MAP_WRITE_BIT_EXT;
using gles::GL_MESH_SHADER_BIT_NV;
using gles::GL_PERFQUERY_GLOBAL_CONTEXT_INTEL;
using gles::GL_PERFQUERY_SINGLE_CONTEXT_INTEL;
using gles::GL_SYNC_FLUSH_COMMANDS_BIT_APPLE;
using gles::GL_TASK_SHADER_BIT_NV;
using gles::GL_TESS_CONTROL_SHADER_BIT;
using gles::GL_TESS_CONTROL_SHADER_BIT_EXT;
using gles::GL_TESS_CONTROL_SHADER_BIT_OES;
using gles::GL_TESS_EVALUATION_SHADER_BIT;
using gles::GL_TESS_EVALUATION_SHADER_BIT_EXT;
using gles::GL_TESS_EVALUATION_SHADER_BIT_OES;
using gles::GL_VERTEX_SHADER_BIT_EXT;


} // namespace gles31ext